version: '3.8'

services:
  app:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/app  # Ensure this mount is appropriate
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      TZ: Europe/Istanbul
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
